# Generated by Django 5.2.3 on 2026-03-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_subjects_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(default='', max_length=255, verbose_name='Адрес')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатно')),
                ('is_free_text', models.CharField(default='', max_length=255, verbose_name='Текст кноки пробного занятия')),
            ],
            options={
                'verbose_name': 'Настройка сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
