# Generated by Django 5.2.3 on 2026-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_settings_alter_subjects_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='cost_first',
            field=models.CharField(default='', max_length=10, verbose_name='Цена пробного занятия'),
        ),
    ]
