# Generated by Django 5.2.3 on 2026-03-16 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_settings_cost_first'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='cost_first',
            field=models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Цена пробного занятия ₽'),
        ),
    ]
