# Generated by Django 5.2.3 on 2026-03-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_settings_cost_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='address',
        ),
        migrations.AddField(
            model_name='settings',
            name='address_1',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AddField(
            model_name='settings',
            name='address_2',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Адрес 2'),
        ),
    ]
