# Generated by Django 5.2.3 on 2026-03-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_settings_address_settings_address_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='is_free_text',
            new_name='button_text',
        ),
    ]
