# Generated by Django 5.2.3 on 2026-03-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_is_free_text_settings_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='button_text',
        ),
        migrations.AddField(
            model_name='settings',
            name='mb_button_text',
            field=models.CharField(default='', max_length=100, verbose_name='Текст кноки на телефоне'),
        ),
        migrations.AddField(
            model_name='settings',
            name='pk_button_text',
            field=models.CharField(default='', max_length=100, verbose_name='Текст кноки на компе'),
        ),
    ]
