# Generated by Django 5.2.3 on 2026-03-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_remove_settings_button_text_settings_mb_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='first_lesson_cost',
            field=models.IntegerField(blank=True, max_length=40, null=True, verbose_name='Цена пробного занятия'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mb_button_text',
            field=models.CharField(default='', max_length=100, verbose_name='Текст кноки на телефоне &nbsp;'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pk_button_text',
            field=models.CharField(default='', max_length=100, verbose_name='Текст кноки на компе &nbsp;'),
        ),
    ]
